### ISSUE TITLE
[EDIT] Incorrect Folder Name 

### ISSUE THREAD

**Issue by coldn00dles** [ComputerSocietyVITC/Annual-Yearbook#11]
the workflow folder containing actions got named as `workflow` instead of `workflows`. Requesting assignees to do the changes.

**Comment by AbhijithGanesh** [comment]
Heyy @coldn00dles ! Welcome to the Annual Yearbook Project. Thanks for pointing out this mistake. It will be patched !

**Comment by cool-pants** [comment]
Issue fixed as of PR #14 . Closing this.
