### ISSUE TITLE
[ADD]: Workflow for updating README

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#13]
## Making a custom workflow
<tr/>

Our current [README](https://github.com/ComputerSocietyVITC/Annual-Yearbook#readme) doesn't update itself when a new contributor commits ! We would like to recognize all of our contributors, so we would like to add a workflow which updates readme.

Links about making a workflow:
- [GitHub's Article on how to make one](https://docs.github.com/en/actions/using-workflows/about-workflows)
- [Making a custom workflow](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
- [Events that trigger a workflow](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)

**Comment by AbhijithGanesh** [comment]
@coldn00dles I request you to help us with this! It is a bit more complex than previous CI/CD tasks

**Comment by coldn00dles** [comment]
surely, i am glad to help

**Comment by 0b51d14n217** [comment]
sure, i can take this.

**Comment by AbhijithGanesh** [comment]
The main challenge here is that, we need to make a new readme everytime we commit ! Please research about it, let us know if you're facing difficulties
