### ISSUE TITLE
[ADD]: Add Issue Templates for the Project

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#2]
## Adding an Issue Template

Most Open Source projects have issue templates carry _Issues and Pull Request_ Templates to help the project maintain some organizational flow. To carry the best practices of Open-Source forward, we would like new forms and templates to be sent in as PULL REQUEST to this repository. Please check the [CONTRIBUTING.md](https://github.com/ComputerSocietyVITC/Annual-Yearbook/blob/master/CONTRIBUTING.md) for reference.

Reference Documentation:
- [GitHub's article on templating](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
- [How to create a template ?](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

**Comment by AbhijithGanesh** [comment]
Related issue: #9

**Comment by icebelly29** [comment]
Hey, I would like to take over this issue
