### ISSUE TITLE
[FEATURE] : Add SEO to the website

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#22]
### Description

Currently, the index page has SEO by adding a title. 

```jsx

import * as React from "react";
import HeaderComponent from "../components/header.jsx";
import Main from "../components/main.jsx";

const IndexPage = () => {
  return (
    <>
      <HeaderComponent />
      <Main />
    </>
  );
};

export default IndexPage;

export const Head = () => <title>Home Page</title>;

```

We need to create a `seo.jsx/seo.tsx` to generate template SEO ! Apart from this the home page title should be changed !

## TL;DR
- [ ] Generate a SEO file
- [ ] Change the head for 404 page
- [ ] Change the head for index page

### Expected Behaviour

- Should improve search engine records for our page

### Current Behaviour

Doesn't have heavy SEO.

### Additional information

Resources:
- [Using React Helmet](https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet/)
- [Using Gatsby's Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/)

**Comment by coldn00dles** [comment]
I can take this issue up
