### ISSUE TITLE
[FEATURE]: Add data for storing profiles

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#24]
### Description

Currently, we don't store the data for our members who intend to store their record ! We would like to create a folder structure to store our users

```
├── data
│   └── 2021
│       └── abhijith-ganesh.json
```

```json
{
  "Name": "Your Name",
  "About": "Your cute tagline",
  "Year_of_graduation": "0000",
  "Links": []
}

```

## TL;DR Check-out the following
- [ ] Add a `data` directory
- [ ] Add years (of graduation) of your preference (possibly 2020, 2021, 2022, 2023...)
- [ ] Add a sample JSON sticking to the format above mentioned

### Expected Behaviour

This Issue should create a directory that would help storing data of interested members!

**Comment by jagadyudha** [comment]
please assign to me @AbhijithGanesh

**Comment by jagadyudha** [comment]
Whose profile will I include? @AbhijithGanesh

**Comment by AbhijithGanesh** [comment]
Yours @jagadyudha
