### ISSUE TITLE
[FEATURE] Add DOCS folder and How to get started ?

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#27]
### Description

We need to have a docs folder which will carry the necessary documentation. This will act as reference on how to get started for our upcoming contributors !

Tasks:
- [x] Add `docs` folder
- [x] Add a brief document about how to get started with the project

### Additional information

References:

- [Contributing Guide](https://github.com/ComputerSocietyVITC/Annual-Yearbook/blob/master/CONTRIBUTING.md)
- [Code of Conduct](https://github.com/ComputerSocietyVITC/Annual-Yearbook/blob/master/CODE_OF_CONDUCT.md)

**Comment by real-zit** [comment]
Please assign this to me

**Comment by 0b51d14n217** [comment]
I can take this!

**Comment by ManavvGarg** [comment]
I would love to takeover this issue and resolve it as quickly as possible!

**Comment by ManavvGarg** [comment]
@AbhijithGanesh I have successfully made and linked a pull request to this issue. Kindly look into it
