### ISSUE TITLE
[ADD]: Add CI/CD actions for the App

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#3]
# CI/CD for application

To make deployments and integrate changes to the repository easy, we usually have GitHub Actions to help us automate and track the changes. You can find the reference Action here, for this issue we would like the contributor to add a workflow which deploys a gatsby-application to a branch names `gh-pages`

**Comment by coldn00dles** [comment]
I would like to take this up

**Comment by AbhijithGanesh** [comment]
@coldn00dles Please link the relevant PR next time! #10 was merged

**Comment by AbhijithGanesh** [comment]
>
