### ISSUE TITLE
[FEATURE] Add new landing page

### ISSUE THREAD

**Issue by ManavvGarg** [ComputerSocietyVITC/Annual-Yearbook#33]
### Designing a new landing page

Design a new minimalistic landing that would be the best fit for the site. Not too fancy, Not too dull.

### Expected Behaviour

N/A

### Current Behaviour

N/A

### Additional information

A folder should be created in the root directory where the design will be saved in .fig files and in PNG format to get a quick glimpse of the website.

While making the design, make sure that it can be implemented smoothly with the current stack.

**Comment by AbhijithGanesh** [comment]
@0b51d14n217 Would you like to work on this!

**Comment by 0b51d14n217** [comment]
> @0b51d14n217 Would you like to work on this!

sure!

**Comment by ManavvGarg** [comment]
Issue closed. The landing page has been added to Design/assets.
