### ISSUE TITLE
[ADD]: Pull Request Template

### ISSUE THREAD

**Issue by AbhijithGanesh** [ComputerSocietyVITC/Annual-Yearbook#9]
As a sub-task of the related issue, please create a pull request template according to the github documentation:

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by vaibhavTekk** [comment]
I would like to work on this issue

**Comment by AbhijithGanesh** [comment]
Heyy @vaibhavTekk ! Welcome to the Annual-Yearbook project ! Welcome to the community

**Comment by cool-pants** [comment]
This issue was fixed as of PR #16. Closing this for now.
